version: '3.3'
services:

  postgres:
    image: postgres:14-alpine
    env_file:
      - .env
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
